# Generated by Django 4.1.4 on 2023-01-25 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homewatch',
            name='display',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='templates'),
            preserve_default=False,
        ),
    ]
