# Generated by Django 4.1.4 on 2023-01-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solid', '0002_homewatch_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewatch',
            name='display',
            field=models.ImageField(upload_to='solid/templates'),
        ),
        migrations.AlterField(
            model_name='homewatch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
