# Generated by Django 4.1.4 on 2023-01-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solid', '0008_blogs_blog_content_blogs_quote_blogs_quote_giver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_content',
            field=models.TextField(max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
