# Generated by Django 4.1.4 on 2023-01-30 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solid', '0009_alter_blogs_blog_content_alter_blogs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_content',
            new_name='blog_paragraph_sub1',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_paragraph_main1',
            field=models.TextField(default=django.utils.timezone.now, max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_paragraph_main2',
            field=models.TextField(default=django.utils.timezone.now, max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_paragraph_main3',
            field=models.TextField(default=django.utils.timezone.now, max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_paragraph_main4',
            field=models.TextField(default=django.utils.timezone.now, max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_paragraph_sub2',
            field=models.TextField(max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_paragraph_sub3',
            field=models.TextField(max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_paragraph_sub4',
            field=models.TextField(max_length=9999, null=True),
        ),
    ]
