# Generated by Django 4.1.4 on 2023-01-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solid', '0010_rename_blog_content_blogs_blog_paragraph_sub1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_paragraph_sub3',
            new_name='blog_paragraph_sub2II',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blog_paragraph_main4',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blog_paragraph_sub4',
        ),
    ]
