# Generated by Django 4.1.4 on 2023-02-01 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solid', '0014_alter_profile_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
