# Generated by Django 4.1.4 on 2023-02-01 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solid', '0015_blogs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_paragraph_main1',
            field=models.TextField(max_length=9999, validators=[django.core.validators.MinLengthValidator(150)]),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
