# Generated by Django 4.1.4 on 2023-02-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solid', '0018_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='blogPage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solid.blogs'),
        ),
    ]
